### ISSUE TITLE
Make the library per monitor DPI aware.

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#31] opened 2018-10-26 11:41 UTC
The current level of DPI awareness of the library is System, and applications using SpTBX should be marked as such using the appropriate manifest file. This means that  the same scaling factor is used for the whole application and the scaling factor is determined when the application is started.   Microsoft has introduced the perMonitorV2 DPI awareness mode. See https://docs.microsoft.com/en-us/windows/desktop/sbscs/application-manifests for details.  This is already the default in Delphi and the forthcoming Delphi 10.3 makes changes to better support it.  With perMonitorV2 every window has its own scaling depending on the monitor it is placed and receives DPI notifications as it moves between monitors.  On older versions of Windows perMonitorV2 only changes the Main form DPI.

This could be the next medium-term target for the library.   The main change required is that all constants that are scaled, need to become instance variables.  Scaling takes place by overriding the ChangeScale virtual method using the window DPI scaling factor.  

When I get some time I will do some work and submit PRs.

**Comment by AlbertWiersch** [comment] 2019-09-06 19:26
Great news. I hope this can be done soon.

I made a video of the problem here:
https://youtu.be/5IfMPVdILyg

**Comment by AlbertWiersch** [comment] 2019-11-19 15:47
Is there any movement on this? It is a big issue for me and I don't want to have to switch components.

**Comment by AlbertWiersch** [comment] 2020-02-24 18:59
I had to release the 2020 version of my application without per monitor DPI support which was disappointing. I think this is the only component holding it back.

So I just wanted to ask/see if there is anyone here who is planning to and able to address this? Or do I need to move to other components (would prefer not to have to though)?

**Comment by pyscripter** [comment] 2020-02-24 19:06
I am planning to do some work on this.

**Comment by AlbertWiersch** [comment] 2020-02-24 19:11
> I am planning to do some work on this soon.

Thank you. That is good news. Are there any estimated time frames of when the work might be completed or ready for testing?

**Comment by pyscripter** [comment] 2020-02-24 19:12
@AlbertWiersch  Not really

**Comment by pyscripter** [comment] 2020-03-02 01:27
I had a go at making SpTBXLib per monitor DPI aware.  The attached zip files contain the changed files.  I have not fully tested yet this new version, but I am showing the work to get some feedback.
[SpTBXLibPerMonitor.zip](https://github.com/SilverpointDev/sptbxlib/files/4272933/SpTBXLibPerMonitor.zip)
[TB2KPerMonitor.zip](https://github.com/SilverpointDev/sptbxlib/files/4272934/TB2KPerMonitor.zip)

For per monitor DPI awareness to work, scaling needs to be done inside a control with a Windows handle.  I have added a class helper in TB2Common:
```
  TControlHelper = class helper for TControl
  public
    (* Scale a value according to the FCurrentPPI *)
    function PPIScale(Value: integer): integer;
    (* Reverse PPI Scaling  *)
    function PPIUnScale(Value: integer): integer;
  end;
```
I have also added virtual protected methods to TTBView and TTBItemViewer 
```
function TTBView.PPIScale(Value: Integer): Integer;
begin
  Result := FWindow.PPIScale(Value);
end;
function TTBItemViewer.PPIScale(Value: Integer): Integer;
begin
  Result := FView.PPIScale(Value);
end;
```
So Controls, Views and ItemViewers can PPIScale things.  The rest should be self-explanatory.

@SilverpointDev Could you please provide some feedback.
@AlbertWiersch Could you please do some testing?

**Comment by pyscripter** [comment] 2020-03-06 00:46
Update:  The implementation is now pretty complete and tested.  The attached zip files contain the changed files:

[SpTBXLibPerMonitor.zip](https://github.com/SilverpointDev/sptbxlib/files/4295852/SpTBXLibPerMonitor.zip)
[TB2KPerMonitor.zip](https://github.com/SilverpointDev/sptbxlib/files/4295851/TB2KPerMonitor.zip)

The only remaining issue I could see is when floating a toolbar and moving it to another monitor.  The problem is that the toolbar ImageList is then wrongly scaled.  Scaling it does not work since it is used in another monitor.  The TTBFloatingWindowParent needs to have its own copy of the ImageList which will be scaled and temporarily assigned it to the toolbar.

**Comment by AlbertWiersch** [comment] 2020-03-06 01:05
Thank you! I hope to try this next week and will report back.

**Comment by AlbertWiersch** [comment] 2020-03-24 14:55
I'm sorry for the delay. All the COVID-19 stuff is slowing me down.

I am getting these errors when I try to build with the changed files:
[dcc64 Error] SpTBXCustomizerForm.pas(142): E2003 Undeclared identifier: 'PPIScale'
[dcc64 Error] SpTBXCustomizerForm.pas(187): E2003 Undeclared identifier: 'PPIScale'
[dcc64 Fatal Error] SpTBXCustomizer.pas(220): F2063 Could not compile used unit 'SpTBXCustomizerForm.pas'

**Comment by pyscripter** [comment] 2020-03-24 15:47
Did you update TB2K files?

**Comment by AlbertWiersch** [comment] 2020-03-24 16:19
Yes, I updated the TB2K files in my "D:\AlC_Components\SpTBX_Rio\tb2k\Source" folder with the 6 files in "TB2KPerMonitor.zip".

**Comment by pyscripter** [comment] 2020-03-24 16:22
Strange because if you look at TB2KCommon.pas you can see PPIScale is defined there as a class helper for TControl.  Which version of Delphi are you using?

**Comment by AlbertWiersch** [comment] 2020-03-24 16:25
Yes, I see this in TB2Common:

```
type
  (*  Helper methods for TControl *)
  TControlHelper = class helper for TControl
  public
    {$IF CompilerVersion <= 31}
    function CurrentPPI: Integer;
    function FCurrentPPI: Integer;
    {$IFEND}
    (* Scale a value according to the FCurrentPPI *)
    function PPIScale(Value: integer): integer;
    (* Reverse PPI Scaling  *)
    function PPIUnScale(Value: integer): integer;
  end;
```

I'm using 10.3 Update 3

**Comment by pyscripter** [comment] 2020-03-24 16:46
Here it compiles fine with the same version of Delphi.

**Comment by AlbertWiersch** [comment] 2020-03-24 17:08
Well this sucks. Not sure what to do. I really wanted to use this.

**Comment by pyscripter** [comment] 2020-03-24 17:17
Actually I haven't tested the customizer.  I used the Overview demo for testing which does not use the Customizer.
Make sure you add the TB2Common to the uses version of SpTBXCustomizerForm

**Comment by AlbertWiersch** [comment] 2020-03-24 18:47
Adding TB2Common to the uses clause fixed one of the errors but not the other one.

I just removed and/or commented out all the 'Customizer' stuff and was able to get it to build. I hope to do some testing and will get back to you.

Ooops... now my app won't compiler:
[ilink64 Error] Fatal: Unable to open file 'SPTBXCUSTOMIZER.O'

Can you fix it so that the attached project will compile?
[SpTBXLib.zip](https://github.com/SilverpointDev/sptbxlib/files/4377101/SpTBXLib.zip)

**Comment by AlbertWiersch** [comment] 2020-03-26 20:26
Hello,

 

Does the following project compile/build for you with the new per-monitor DPI support?

 

I really appreciate the work you’ve done with this… I think it’s almost there so I’m hoping this can be resolved easily.

 

--

Albert Wiersch

CSS HTML Validator 

support@htmlvalidator.com

https://www.htmlvalidator.com/

**Comment by AlbertWiersch** [comment] 2020-04-02 16:13
Has anyone been able to compile the attached project with the per-monitor DPI changes?
[SpTBXLib.zip](https://github.com/SilverpointDev/sptbxlib/files/4422207/SpTBXLib.zip)

**Comment by pyscripter** [comment] 2020-04-02 21:11
@AlbertWiersch Why don't you try to make it work yourself.  It can't be that hard.

**Comment by AlbertWiersch** [comment] 2020-04-03 01:47
@pyscripter , I tried. I'm a C++ guy and not familiar with Delphi and building components. I was able to get rid of one of the errors by adding TB2Common to a uses clause but it didn't fix the other error.

**Comment by AlbertWiersch** [comment] 2020-05-25 21:43
Well I gave this another shot to see if I could use it in my upcoming minor software update. I was able to figure out how to get it to compile.

Unfortunately it doesn't work for my main application window where most of my TSpTBX components are used. If I launch my software on my 4K monitor w/175% scaling, it looks pretty good on the 4K monitor. However, when I move it to a 1920x1080 monitor at 100% scaling, it flickers quite a bit and the toolbar menu text (TSpTBXToolbar on a TSpTBXDock) ends up way too small, like it resized it down 2 or more times (could it be resizing more than once causing all the flickering and the incorrect size?). If I move the window back to the 4K/175% monitor then it restores and looks correct again.

**Comment by pyscripter** [comment] 2020-05-26 05:55
You have to scale your images every time the form changes monitor for this to work.   Delphi Rio 10.3 introduced VirtualImagesList  that does that.  Otherwise you need to scale them manually.  See for example http://zarko-gajic.iz.hr/resizing-delphis-timagelist-bitmaps-to-fit-high-dpi-scaling-size-for-menus-toolbars-trees-etc/

**Comment by AlbertWiersch** [comment] 2020-05-26 14:34
Yes, I use TVirtualImageList and it works quite well. The problem is the font size (like for the main menu), not image size. If you want to help me look into this issue then I can send you my app so you can try it for yourself, or a screenshot or something..... but first I need to get my minor update out and then do a little more testing & investigation to make sure it's not something I'm doing.

**Comment by pyscripter** [comment] 2020-09-22 04:28
A PR #56 has been submitted with a complete implementation of Per Monitor DPI awareness.

Please note:
- I have tried to remain backward compatible, but I have not tested with old versions of Delphi.
- The TB2K patch has also been updated
- To reduce flicker when moving forms between monitors on can use
LockWindowUpdate(Handle)
LockWindowUpdate(0)
in the Form event handlers for OnBefore/AfterMonitorDpiChanged

**Comment by SilverpointDev** [comment] 2020-10-08 14:09
Thank you! I'll take a look

**Comment by SilverpointDev** [comment] 2020-11-10 18:37
I've updated the lib with all the changes made by Pyscripter with some modifications. It needs more testing. Not sure how to handle DockablePanels, if all the sizes should be scaled or not (MinClientWidth/MinClientHeight, FloatingClientWidth/FloatingClientHeight).
The TB2K patch was updated by Pyscripter, TB2K needs to be patched again.

**Comment by pyscripter** [comment] 2020-11-10 20:30
Thanks!  I will be doing some testing.

**Comment by AlbertWiersch** [comment] 2020-12-07 23:18
> I've updated the lib with all the changes made by Pyscripter with some modifications. It needs more testing. Not sure how to handle DockablePanels, if all the sizes should be scaled or not (MinClientWidth/MinClientHeight, FloatingClientWidth/FloatingClientHeight).
> The TB2K patch was updated by Pyscripter, TB2K needs to be patched again.

Well, I'm not a component designer but I assume the Width and Height attributes are updated so it would seem logical to me to also update the Min and Max widths and heights and other widths and heights that would be affected by the DPI change?

**Closed** 2021-01-04 16:14 UTC
