### ISSUE TITLE
Error paint TSpTBXSubmenuItem when entering in a TSpTBXSpinEditItem

### ISSUE THREAD

**Issue by morgancdip** [SilverpointDev/sptbxlib#110] opened 2023-10-05 11:01 UTC
Hi,
I'm using version 2.5.10.

Here's how it looked before the bug:  
![image](https://github.com/SilverpointDev/sptbxlib/assets/36631246/ea4eb891-c9aa-4567-9eab-bd60231e64d4)

Here's how to enter in the TSpTBXSpinEditItem:  
![image](https://github.com/SilverpointDev/sptbxlib/assets/36631246/465909a0-4a9c-4242-8d45-52009e880eca)

This is due to the activation of this option: 
![image](https://github.com/SilverpointDev/sptbxlib/assets/36631246/ca2e660a-5994-445b-9869-e6aae3297d05)

Can you find out how to fix this problem?

Thanks

**Comment by SilverpointDev** [comment] 2023-10-06 12:33
I can't reproduce it, can you post a simple demo?

**Comment by morgancdip** [comment] 2023-10-06 15:12
Here is a test project: 
[TestSTBX.zip](https://github.com/SilverpointDev/sptbxlib/files/12832638/TestSTBX.zip)

However, in the test project, it doesn't happen every time.
I manage to make the bug appear when you click on the label just above and then click on the edge of the SpinEdit.
Here's an example video:
[bug_SpTBX.webm](https://github.com/SilverpointDev/sptbxlib/assets/36631246/7704a677-d5a4-4766-8bdc-882a03f5c75c)

**Comment by SilverpointDev** [comment] 2023-10-11 17:56
Fixed on latest commit

**Closed by SilverpointDev** 2023-10-11 17:56 UTC
