### ISSUE TITLE
Drop down arrow is drawn behind the image

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#86] opened 2021-04-05 05:55 UTC
Commit https://github.com/SilverpointDev/sptbxlib/commit/4db3ebb80fe48d4a301383bb5e6d781d2fc353e4 broke the painting of dropdown arrows.

To reproduce drop a TSpTBXSubmenuItem on a Toolbar and set its Options to [tboDropdownArrow].  Keep DropDownCombo to False.

This is the part of the code in SpTBXItem.pas that is to blame:

```pascal
  R := ClientAreaRect;
  if ItemInfo.ToolbarStyle then begin
    if ItemInfo.HasArrow then begin
      ItemInfo.ComboRect := R;
      if ItemInfo.IsSplit then begin
        Dec(R.Right, SplitBtnArrowSize);
        ItemInfo.ComboRect.Left := R.Right;
      end
      else
        if not IsSpecialDropDown then begin
          // If the caption is shown calculate the right margin, if the caption
          // is not visible center the arrow
          if TextInfo.IsCaptionShown then
            if View.Orientation <> tbvoVertical then
              ItemInfo.ComboRect := Rect(R.Right - Self.tbDropdownArrowWidth - Self.tbDropdownArrowMargin, 0,
                R.Right - Self.tbDropdownArrowMargin, R.Bottom)
            else
              ItemInfo.ComboRect := Rect(0, R.Bottom - Self.tbDropdownArrowWidth - Self.tbDropdownArrowMargin,
                R.Right, R.Bottom - Self.tbDropdownArrowMargin);
        end
        else begin
```
ItemInfo.ComboRect is initialized with the ClientAreRect.  
If 
- ItemInfo.HasArrow is True
-  ItemInfo.IsSplit is False
- IsSpecialDropDown is False
- TextInfo.IsCaptionShown is False

then  Item.ComboRect still points to the ClientRect and the arrow is centered in that area.   And if  SpTBXItem has an image the arrow is painted behind the image.

The commit added the           
`if TextInfo.IsCaptionShown then
`
statement but did not provide the else part.
Before the commit the code was working fine when there is an image but no label.

**Comment by MShark67** [comment] 2021-04-05 10:00
Just a note that this is a dupe of #84.  I've been running this fix for a month with no issues that I've seen.

**Comment by pyscripter** [comment] 2021-04-05 12:14
@MShark67 Yes indeed.  I am really sorry I missed that.  And my fix is the same as yours.

**Comment by MShark67** [comment] 2021-04-05 13:07
No worries!  Your report may get more attention (and deservedly so, your contributions are always top notch!)

**Comment by SilverpointDev** [comment] 2021-04-12 18:01
Fixed

**Closed by SilverpointDev** 2021-04-12 18:01 UTC
