### ISSUE TITLE
SpTBXTabSet rendering glitches when SpTBX skin is enabled

### ISSUE THREAD

**Issue by charlesw** [SilverpointDev/sptbxlib#54] opened 2019-12-02 04:42 UTC
Steps to reproduce:

1. Add SpTBXTabSet with two tabs to a form 
2. Set the SpTBX skin to "Office 2007 Blue"
3. Run app and switch between tabs, note that all tabs disappear until refreshed by moving mouse

Note that a Delphi example demonstrating the bug can be found here: https://github.com/charlesw/sptbxlib (see delphi project in Demos/SpTBXTabSetBug)

Other things to note: 

* The problem only happens when SpTBX has been configured to use a skin, Office 2007 Blue in this case but I tried a selection of the others and they all had the same issue.
* Reproduced against master & tb2k 2.2.2 with latest patch from master applied

**Comment by charlesw** [comment] 2020-01-06 23:10
I've had a bit more of a look into this appears to be occurring as Toolbar that renders the tabs will only render the tabs that intersect with the current clipping rectangle. While this makes sense something changed since 2.4.8 (the last version we used) which means that when the active tab is changed the inactive ones aren't rendered resulting in blank background being displayed in their place.

I've managed to work around the issue by forcing a full invalidation when the active tab changes by calling TSpTBXTabToolbar.InvalidateNC rather than using View.InvalidatePosition & SetWinPos in TSpTBXTabToolbar.SetActiveTabIndex. According to the comments in the code this may cause flicker though we haven't noticed any in our specific circumstance.

**Comment by SilverpointDev** [comment] 2020-01-20 14:50
Can't reproduce, tried your demo and it works fine.
Can you try to reproduce it with TSpTBXStatusBar?

**Comment by charlesw** [comment] 2020-01-30 06:47
No I've only noticed it on the tabset. If you can't reproduce all I can
think is it might be some interaction with vcl, we use Rad Studio 10.2.3,
though it is odd that past releases were fine. Unfortunately I don't
currently have access to 10.3 series so can't test it in that.

**Comment by SilverpointDev** [comment] 2020-01-30 16:12
I have tested it with 10.2.3
Are you sure you applied the latest patch to TB2K?

**Comment by charlesw** [comment] 2020-01-31 03:04
Yes the latest version of the patch was applied to TB2K 2.2.2. 

Just to be clear this is the kind of glitches I'm seeing:
![image](https://user-images.githubusercontent.com/259016/73508672-c906b380-4430-11ea-8a82-2ef475914a0f.png)

I've also updated my forked repo\demo to reflect the latest code and can confirm it still occurs.

**Comment by SilverpointDev** [comment] 2020-02-04 15:17
Can't reproduce it on your demo.
Can you try this, change the following methods:

procedure TSpTBXTabToolbarView.BeginUpdate;
begin
  inherited;
end;

procedure TSpTBXTabToolbarView.EndUpdate;
begin
  inherited;
  if (FUpdating = 0) and (Owner is TSpTBXTabToolbar) then
    TSpTBXTabToolbar(Owner).InvalidateNC;
end;

**Comment by charlesw** [comment] 2020-02-04 20:31
Tried the change you suggested and it doesn't work, neither is BeginUpdate or EndUpdate ever called (in the demo)

**Comment by SilverpointDev** [comment] 2020-11-28 13:25
Fixed in latest commit

**Closed by SilverpointDev** 2020-11-28 13:25 UTC
